apiVersion: v1
kind: Pod
metadata:
  name: pvc-uploader
spec:
  restartPolicy: Never
  containers:
  - name: uploader
    image: busybox
    command: ["sleep", "36000"]

    volumeMounts:
    - name: data
      mountPath: /mnt/data

    - name: faiss
      mountPath: /mnt/faiss

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-pvc

  - name: faiss
    persistentVolumeClaim:
      claimName: faiss-pvc