apiVersion: v1
kind: Service

metadata:
  name: legal-analysis-service

spec:
  selector:
    app: legal-analysis

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP