apiVersion: v1
kind: Service
metadata:
  name: legal-analysis-service
  annotations:
    argocd-test: "1"
spec:
  type: NodePort
  selector:
    app: legal-analysis
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080